// generated by Fast Light User Interface Designer (fluid) version 1.0311

#ifndef graphics_gui_h
#define graphics_gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *MainWindow;
#include <FL/Fl_Tile.H>
extern Fl_Tile *Title;
#include <FL/Fl_Box.H>
extern Fl_Box *DrawingBox;
Fl_Double_Window* make_window();
#endif
