// generated by Fast Light User Interface Designer (fluid) version 1.0311

#include "graphics_gui.h"

Fl_Double_Window *MainWindow=(Fl_Double_Window *)0;

Fl_Tile *Title=(Fl_Tile *)0;

Fl_Box *DrawingBox=(Fl_Box *)0;

Fl_Double_Window* make_window() {
  { MainWindow = new Fl_Double_Window(810, 535);
    MainWindow->box(FL_UP_BOX);
    { Title = new Fl_Tile(20, 25, 775, 505, "Graphics");
      Title->box(FL_UP_BOX);
      Title->color((Fl_Color)48);
      { DrawingBox = new Fl_Box(45, 50, 720, 450);
        DrawingBox->box(FL_ENGRAVED_FRAME);
      } // Fl_Box* DrawingBox
      Title->end();
      Fl_Group::current()->resizable(Title);
    } // Fl_Tile* Title
    MainWindow->end();
  } // Fl_Double_Window* MainWindow
  return MainWindow;
}
